# language: node_js
# node_js:
#   - "14"

# script:
#   - cd api
#   - cd .. && cd client && npm install && npm run lint && npm run test
language: node_js
node_js:
  - "14"
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: Lint, Test
      name: Lint
      script:
        - npm install
        - npm run lint
    - name: Test
      script:
        - npm install
        - npm test
    - name: Build
      script:
        - npm install
        - npm run build
branches:
  only:
  - main
  - unitTest